# Generated by Django 5.2.8 on 2025-11-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('solution', models.TextField()),
                ('affected_plants', models.ManyToManyField(blank=True, related_name='diseases', to='plants.plant')),
            ],
        ),
    ]
